@echo off
echo Adding changes...
git add .
echo Committing changes...
git commit -m "feat: standard naming, skills as prompts, admin dashboard updates, and user tracking improvements"
echo Switching to main...
git checkout main
echo Merging changes...
git merge refactor/apps-split-legacy-removal
echo Pushing to main...
git push origin main
echo Done.
