/**
 * create_api_endpoint skill: creates a minimal API endpoint (controller + route).
 * Orchestrates create_file to add controller and route files.
 */

import { z } from "zod";
import type { SkillDefinition } from "../types/skills.js";
import type { ToolCallResult } from "../types/tools.js";
import { executeTool } from "../tools/index.js";

export const CREATE_API_ENDPOINT_NAME = "create_api_endpoint" as const;

const inputSchema = {
  name: z
    .string()
    .describe("Endpoint/action name (e.g. getUser, createItem)"),
  path: z
    .string()
    .describe("URL path for the endpoint (e.g. /api/users, /api/items)"),
  method: z
    .enum(["GET", "POST", "PUT", "PATCH", "DELETE"])
    .default("GET")
    .describe("HTTP method"),
  controllerDir: z
    .string()
    .optional()
    .default("src/controllers")
    .describe("Directory for controller file (relative to workspace)"),
  routeDir: z
    .string()
    .optional()
    .default("src/routes")
    .describe("Directory for route file (relative to workspace)"),
};

export type CreateApiEndpointArgs = z.infer<z.ZodObject<typeof inputSchema>>;

async function handler(args: CreateApiEndpointArgs): Promise<ToolCallResult> {
  const created: string[] = [];
  const controllerName =
    args.name.charAt(0).toUpperCase() + args.name.slice(1) + "Controller";
  const controllerPath = `${args.controllerDir}/${controllerName}.ts`;
  const routePath = `${args.routeDir}/index.ts`;

  const controllerContent = `/**
 * ${controllerName} - generated by create_api_endpoint skill.
 */
export async function ${args.name}(req: unknown, res: unknown): Promise<void> {
  // TODO: implement ${args.method} ${args.path}
}
`;

  const routeContent = `/**
 * Route registration for ${args.path} - generated by create_api_endpoint skill.
 */
// TODO: register ${args.method} ${args.path} -> ${controllerName}.${args.name}
`;

  try {
    const createResult = await executeTool("create_file", {
      path: controllerPath,
      content: controllerContent,
    });
    if (createResult.isError) {
      return createResult;
    }
    created.push(controllerPath);

    const routeResult = await executeTool("create_file", {
      path: routePath,
      content: routeContent,
    });
    if (routeResult.isError) {
      return {
        content: [
          {
            type: "text",
            text: `Controller created at ${controllerPath}. Route step failed: ${routeResult.content[0]?.text ?? "unknown"}`,
          },
        ],
        isError: true,
      };
    }
    created.push(routePath);

    return {
      content: [
        {
          type: "text",
          text: `Created API endpoint: ${args.method} ${args.path}\nFiles: ${created.join(", ")}`,
        },
      ],
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      content: [{ type: "text", text: `Error: ${message}` }],
      isError: true,
    };
  }
}

export const createApiEndpointSkill: SkillDefinition<CreateApiEndpointArgs> = {
  name: CREATE_API_ENDPOINT_NAME,
  description:
    "Create a minimal API endpoint: adds a controller file and a route file. Optional controllerDir and routeDir (default src/controllers, src/routes). Swagger/codegen can be added later.",
  inputSchema,
  handler,
};
